name: Main Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      release-type:
        description: "Choose release type"
        required: true
        default: "release"
        type: choice
        options:
          - release

jobs:
  determine_workflow:
    runs-on: ubuntu-latest
    outputs:
      workflow_type: ${{ steps.set-workflow.outputs.workflow_type }}
      version: ${{ steps.set-workflow.outputs.version }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Determine workflow type and version
        id: set-workflow
        run: |
          # Get version from package.json
          VERSION=$(node -e "console.log(require('./package.json').version);")
          echo "version=${VERSION}" >> $GITHUB_OUTPUT

          # Set workflow type based on trigger
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "workflow_type=release" >> $GITHUB_OUTPUT
            echo "Running release workflow v${VERSION}"
          else
            echo "workflow_type=main" >> $GITHUB_OUTPUT
            echo "Running development workflow v${VERSION}"
          fi

  init_flow:
    needs: determine_workflow
    uses: ./.github/workflows/init.yml
    with:
      workflow_type: ${{ needs.determine_workflow.outputs.workflow_type }}
      version: ${{ needs.determine_workflow.outputs.version }}
    secrets: inherit

  build_flow:
    needs: [determine_workflow, init_flow]
    uses: ./.github/workflows/build.yml
    with:
      workflow_type: ${{ needs.determine_workflow.outputs.workflow_type }}
      version: ${{ needs.determine_workflow.outputs.version }}
    secrets: inherit

  deploy_flow:
    needs: [determine_workflow, build_flow]
    uses: ./.github/workflows/deploy.yml
    with:
      workflow_type: ${{ needs.determine_workflow.outputs.workflow_type }}
      version: ${{ needs.determine_workflow.outputs.version }}
    secrets: inherit

  pre_marketplace_flow:
    needs: [determine_workflow, deploy_flow]
    if: needs.determine_workflow.outputs.workflow_type == 'release'
    uses: ./.github/workflows/pre_marketplace.yml
    with:
      version: ${{ needs.determine_workflow.outputs.version }}
    secrets: inherit

  marketplace_push_flow:
    needs: [determine_workflow, pre_marketplace_flow]
    if: needs.determine_workflow.outputs.workflow_type == 'release'
    uses: ./.github/workflows/marketplace_push.yml
    with:
      version: ${{ needs.determine_workflow.outputs.version }}
      staging_account_id: ${{ needs.pre_marketplace_flow.outputs.staging_account_id }}
      confirm_push: false
    secrets: inherit

  electron_flow:
    needs: [determine_workflow, deploy_flow]
    uses: ./.github/workflows/electron.yml
    with:
      workflow_type: ${{ needs.determine_workflow.outputs.workflow_type }}
      version: ${{ needs.determine_workflow.outputs.version }}
    secrets: inherit
